openapi: 3.0.4
info:
  title: Code Detector
  description: >-
    Code Detector is a simple tool for detecting the language of code in text.
    It returns details such as extension, language, family, and more.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.0
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
  - url: https://api.apiverve.com/
paths:
  /v1/codedetector:
    post:
      summary: Detect Code
      description: >-
        Code Detector is a simple tool for detecting the language of code in
        text. It returns details such as extension, language, family, and more.
      operationId: codedetector
      parameters: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: object
                    description: data
              example:
                status: ok
                error: null
                data:
                  likelihood: 0.99
                  family: PYTHON
                  current: python
                  readable: Python Code
                  extension: .py
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occurred, try again later
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
                  description: >-
                    The code snippet you want to detect the programming language
                    of
              required:
                - code
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
  - api_key: []
sampleRequest:
  code: |-
    a = 5
    b = 6
    c = 7

    # calculate the semi-perimeter
    s = (a + b + c) / 2

    # calculate the area
    area = (s*(s-a)*(s-b)*(s-c)) ** 0.5
    print('The area of the triangle is %0.2f' %area)
