name: apiverve_codedetector
description: Code Detector is a simple tool for detecting the language of code in text. It returns details such as extension, language, family, and more.
version: 1.1.14
homepage: https://apiverve.com/marketplace/codedetector?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/codedetector-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
